version: '3.7'
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mendoza
      - SERVERPORT=51820 #optional
      - SERVERURL= #opcional publica server
      - PEERS=2 #optional - host a conectarse
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional (rango que entrega la vpn)
      - ALLOWEDIPS= 0.0.0.0/0 #opcional- Desde donde se pueden conectar
    volumes:
      - /root/wireguard:/config
      - /lib/modules:/lib/modules
      - /usr/src:/usr/src
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    dns:
      - 172.20.0.7
    restart: unless-stopped
    networks:
      containers:
        ipv4_address: 172.20.0.6
    networks:
      containers:
        ipv4_address: 172.20.0.7
networks:
  containers:
    ipam:
      config:
        - subnet: 172.20.0.0/24
